# fly.toml app configuration file generated for Portfolio CreAA app on platform Fly.io
# See https://fly.io/docs/reference/configuration-reference/ for information about all supported options.

app = "portfolio-creaa"
primary_region = "cdg"

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  processes = ["app"]

  [services.http_checks]
    enabled = true
    interval = 10000
    timeout = 5000
    grace_period = "5s"
    method = "get"
    path = "/"
    protocol = "http"
    tls_skip_verify = false

[[services.ports]]
  port = 80
  handlers = ["http"]
  force_https = true

[[services.ports]]
  port = 443
  handlers = ["tls", "http"]
